name: flutter_defualt_project
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.6
  zoom_tap_animation: ^1.1.0
  flutter_screenutil: ^5.8.4
  change_app_package_name: ^1.1.0
  easy_localization: ^3.0.2
  shared_preferences: ^2.1.2
  http: ^1.1.0
  url_launcher: ^6.1.11
  cached_network_image: ^3.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  path: ^1.8.3
  mask_text_input_formatter: ^2.4.0
  carousel_slider: ^4.2.1
  like_button: ^2.0.5
  image_picker: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/svg/
    - assets/translations/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Montserrat-Black.ttf
        - asset: assets/fonts/Poppins/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/Poppins/Montserrat-Bold.ttf
        - asset: assets/fonts/Poppins/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/Poppins/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Poppins/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/Poppins/Montserrat-ExtraLightItalic.ttf
        - asset: assets/fonts/Poppins/Montserrat-Italic.ttf
        - asset: assets/fonts/Poppins/Montserrat-Light.ttf
        - asset: assets/fonts/Poppins/Montserrat-LightItalic.ttf
        - asset: assets/fonts/Poppins/Montserrat-Medium.ttf
        - asset: assets/fonts/Poppins/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/Poppins/Montserrat-Regular.ttf
        - asset: assets/fonts/Poppins/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Poppins/Montserrat-SemiBoldItalic.ttf
        - asset: assets/fonts/Poppins/Montserrat-Thin.ttf
        - asset: assets/fonts/Poppins/Montserrat-ThinItalic.ttf
          style: italic


    - family: Work Sans
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Black.ttf
        - asset: assets/fonts/Work_Sans/WorkSans-BlackItalic.ttf
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf
        - asset: assets/fonts/Work_Sans/WorkSans-BoldItalic.ttf
        - asset: assets/fonts/Work_Sans/WorkSans-ExtraBold.ttf
        - asset: assets/fonts/Work_Sans/WorkSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/Work_Sans/WorkSans-ExtraLight.ttf
        - asset: assets/fonts/Work_Sans/WorkSans-ExtraLightItalic.ttf
        - asset: assets/fonts/Work_Sans/WorkSans-Italic.ttf
        - asset: assets/fonts/Work_Sans/WorkSans-Light.ttf
        - asset: assets/fonts/Work_Sans/WorkSans-LightItalic.ttf
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
        - asset: assets/fonts/Work_Sans/WorkSans-MediumItalic.ttf
        - asset: assets/fonts/Work_Sans/WorkSans-Regular.ttf
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBoldItalic.ttf
        - asset: assets/fonts/Work_Sans/WorkSans-Thin.ttf
        - asset: assets/fonts/Work_Sans/WorkSans-ThinItalic.ttf
          style: italic


    - family: Playfair
      fonts:
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-Black.ttf
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-BlackItalic.ttf
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-Bold.ttf
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-BoldItalic.ttf
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-ExtraBold.ttf
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-ExtraBoldItalic.ttf
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-Italic.ttf
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-Medium.ttf
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-MediumItalic.ttf
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-SemiBold.ttf
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-SemiBoldItalic.ttf
          style: italic